### ISSUE TITLE
emit the event after in the setup with all parameters listed and the current owner

### ISSUE THREAD

**Issue by PawelTroka** [ToucanProtocol/dynamic-fee-pools#24]
I think another good practice would be to emit the event after in the setup with all parameters listed and the current owner

_Originally posted by @kosecki123 in https://github.com/neutral-protocol/dynamic-fee-pools/issues/23#issuecomment-1838366317_

**Comment by 0xmichalis** [comment]
Fixed by https://github.com/ToucanProtocol/dynamic-fee-pools/pull/43
